services:

  recipe-application:
    image: "askie01/recipe-application:latest"
    container_name: "recipe-application"
    ports:
      - "8080:8080"
    environment:
      - "spring.datasource.url=jdbc:mysql://recipe-database:3306/recipes"
      - "spring.datasource.username=${recipe_database_username}"
      - "spring.datasource.password=${recipe_database_password}"
    networks:
      - recipe-application-network
    tty: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      recipe-database:
        condition: service_healthy

  recipe-database:
    image: "mysql:latest"
    container_name: "recipe-database"
    ports:
      - "3306:3306"
    volumes:
      - "./sql/schema/mysql:/docker-entrypoint-initdb.d"
      - "./sql/data:/var/lib/mysql"
    environment:
      - "MYSQL_USER=${recipe_database_username}"
      - "MYSQL_PASSWORD=${recipe_database_password}"
      - "MYSQL_DATABASE=recipes"
      - "MYSQL_ROOT_PASSWORD=${recipe_database_root_password}"
    networks:
      - recipe-application-network
    tty: true
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  recipe-application-network:
    driver: bridge