server:
  port: 8080

spring:
  application:
    name: recipe-application

  datasource:
    url: jdbc:mysql://localhost:3306/recipe_database
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none

  docker:
    compose:
      enabled: true

  data:
    jdbc:
      dialect: mysql

component:
  auditor:
    type: service
  validator:
    id-type: positive-long-id
    image-type: five-mega-bytes
    name-type: non-blank-string
    servings-type: positive-servings
    cooking-time-type: positive-cooking-time
    instructions-type: non-blank-instructions
    version-type: positive-long-version
  mapper:
    id-type: validated-long-id
    image-type: validated-image
    name-type: validated-string-name
    servings-type: validated-servings
    cooking-time-type: validated-cooking-time
    instructions-type: validated-instructions
    version-type: validated-long-version
    difficultyDTO-to-difficulty-type: simple
    categoryDTO-to-category-type: simple
    measureUnitDTO-to-measureUnit-type: simple