server:
  port: 8080

spring:
  application:
    name: recipe-application

  datasource:
    url: jdbc:mysql://localhost:3306/recipe_database
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none

  docker:
    compose:
      enabled: true

  data:
    jdbc:
      dialect: mysql

component:
  auditor:
    type: service
  validator:
    id-type: positive-long-id
    image-type: five-mega-bytes
    name-type: non-blank-string
    servings-type: positive-servings
  mapper:
    id-type: validated-long-id
    image-type: validated-image
    name-type: validated-string-name